### ISSUE TITLE
Missing showDialog() from BuildTwoPhaseDialog.java

### ISSUE THREAD

**Issue by istvangal** [mariosangiorgio/RateMyApp#20]
Just a snippet: I tried to use 1.1-master, but BuildTwoPhaseDialog.java is missing a

```
dialogBuilder.show();
```

on line 28.

**Comment by mariosangiorgio** [comment]
I have been quite busy lately and I still have to catch up with that bug.

Do you think this bug could be related to this other issue? https://github.com/mariosangiorgio/RateMyApp/issues/19

Since you seem to have a fix for the bug, would you mind to fork the project and create a pull request? It would be really appreciated and it would speed up the release of a new version containing the fix

**Comment by istvangal** [comment]
Sure, I'll create a pull request soon.
As of #19, it seems like the reason is the same.
